version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: instagram_crawler_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  crawler:
    build: .
    container_name: instagram_crawler
    restart: always
    depends_on:
      - postgres
    command: ["sh", "-c", "sleep 5 && python -m crawler.main"]

volumes:
  pg_data: